// 古曰：易辞不易客文。今释：验证默认语言、共享 cookie、导航与原始日志保护。
import {test} from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';
const {JSDOM,CookieJar}=await import(process.env.YY_DOM_MODULE||'jsdom');
const 脚本=await readFile(new URL('../共用/界面.js',import.meta.url),'utf8');
const 页=(url,jar)=>new JSDOM('<body><div data-yuyan-site="playground" data-home="/"></div><main><p data-han="现代文本" data-wen="古辞">现代文本</p><p id="动态">正在连接编译室…</p><pre id="源码">显示</pre><div role="log">显示</div><details id="日志面板"><summary>对话与调试日志</summary></details><pre id="编译日志" hidden>编译</pre></main></body>',{url,runScripts:'outside-only',cookieJar:jar});
test('默认汉语，切换共享偏好且保留原始数据和折叠状态',async()=>{const jar=new CookieJar(),dom=页('https://playground.yuyan-lang.org/',jar);dom.window.eval(脚本);const d=dom.window.document;assert.equal(d.documentElement.lang,'zh-CN');assert.equal(d.querySelector('.豫标志').href,'https://yuyan-lang.org/');assert.equal(d.querySelector('.豫站名').href,'https://playground.yuyan-lang.org/');d.querySelector('[data-lang=wen]').click();await new Promise(r=>setTimeout(r,10));assert.equal(d.querySelector('[data-han]').textContent,'古辞');assert.equal(d.getElementById('动态').textContent,'正候编译室…');assert.equal(d.getElementById('源码').textContent,'显示');assert.equal(d.querySelector('[role=log]').textContent,'显示');assert.equal(d.getElementById('日志面板').open,false);assert.equal(d.getElementById('编译日志').hidden,true);const second=页('https://yuyan-lang.org/',jar);second.window.eval(脚本);assert.equal(second.window.document.documentElement.lang,'lzh');d.querySelector('[data-lang=han]').click();assert.equal(d.getElementById('动态').textContent,'正在连接编译室…');dom.window.close();second.window.close();});
test('异步界面更新可翻译，源码与未知错误保持原文',async()=>{const dom=页('https://playground.yuyan-lang.org/?lang=wen',new CookieJar());dom.window.eval(脚本);const d=dom.window.document;d.getElementById('动态').textContent='编译室正忙，请稍后重试';await new Promise(r=>setTimeout(r,10));assert.equal(d.getElementById('动态').textContent,'编译室方有事，请稍候复试');d.getElementById('动态').textContent='custom diagnostic';await new Promise(r=>setTimeout(r,10));assert.equal(d.getElementById('动态').textContent,'custom diagnostic');dom.window.close();});

test('主站入口固定上游，不把访客认证传给 Pages',async()=>{const {default:桥,原站地址}=await import('../入口/云桥.mjs');assert.equal(原站地址('https://yuyan-lang.org/教程/?lang=wen').href,'https://yuyan-lang.github.io/yuyan/%E6%95%99%E7%A8%8B/');const 原fetch=globalThis.fetch;try{globalThis.fetch=async(url,opts)=>{assert.equal(url.origin,'https://yuyan-lang.github.io');assert.equal(opts.headers.has('authorization'),false);assert.equal(opts.headers.has('cookie'),false);return new Response('ok',{headers:{'Content-Type':'text/plain'}});};const r=await 桥.fetch(new Request('https://yuyan-lang.org/a',{headers:{Authorization:'secret',Cookie:'private=1'}}));assert.equal(await r.text(),'ok');assert.equal((await 桥.fetch(new Request('https://yuyan-lang.org/',{method:'POST'}))).status,405);}finally{globalThis.fetch=原fetch;}});
