/* 古曰：汉语为始，文言可易；客书原录，不妄改之。今释：同域 cookie 共享偏好，仅翻译界面，保留代码和日志。 */
(()=>{
const 站=document.querySelector('[data-yuyan-site]');if(!站)return;
const 主站='https://yuyan-lang.org',试写='https://playground.yuyan-lang.org/',包站='https://包管理.yuyan-lang.org/';
const 名称={home:['首页','首页'],tutorial:['教程','学篇'],docs:['接口文档','接口之文'],source:['源码浏览','源码观览'],playground:['试写间','试写间'],packages:['包管理','包府']};
const 类型=站.dataset.yuyanSite;document.documentElement.dataset.yuyan=类型;
const 参数=new URL(location.href).searchParams.get('lang');
let 语言=['han','wen'].includes(参数)?参数:document.cookie.match(/(?:^|; )yuyan_lang=(han|wen)(?:;|$)/)?.[1]||'han';
const 词={ '模块目录':'模块之目','接口参考':'接口之录','静态生成':'静态生成','公开名称':'公开之名','公开':'公开','暂无说明。':'尚无说明。','此模块没有公开名称。':'此模块无公开之名。','选择模块，查看其公开名称、中文类型与源码注释。':'择模块以观公开之名、中文类型与源码之注。','▶ 运行':'▶ 行之','点击「运行」，在这里查看结果。':'按运行，于此观其果。','等待编译器输出…':'待编译器所出…','点击运行或生成后，编译器的实时输出会直接显示在这里。':'按运行或生成，编译之出随至随示。','判断请求范围':'审其所请','准备隔离空间与标准库缓存':'备别室与标准库缓存','正在编译（最多 30 秒）':'正编其文（限三十秒）','编译通过，正在运行（最多 5 秒）':'编已成，正行之（限五秒）','服务尚未连接':'尚未通服务','编译室准备中 · 可先编辑代码':'编译室未备 · 可先书稿','暂未连接到编译室':'尚未通编译室','编译室已就绪 · AI 待配置':'编译室已备 · AI 待置','复制代码':'复制此文', '教程':'学篇','文档':'文档','包管理':'包府','在线体验':'在线试写','菜单':'目录','跳到正文':'直至正文','返回顶部 ↑':'返于篇首 ↑','由豫言静态生成':'豫言成此静页','入口':'始于','模块':'模块','名称':'名','模块星图':'模块目录','沿依赖闭包浏览公开接口。':'循依赖而阅公开之名。','全部模块':'诸模块','← 全部模块':'← 诸模块','公开接口':'公开之名','浏览项目文件与源码':'观诸文件与源码','选择文件查看源码':'择书以观其文','文件':'文件','源码树':'源码目录','阅读设置':'观览之制','豫言源码浏览器':'豫言源码观览','正在连接编译室…':'正候编译室…','写下所想，让文字运行':'书其所思，使文可行','你的第一段豫言。':'试书豫言。','与豫言共写':'与豫言共书','从一个想法开始。':'始于一念。','描述你想写的程序，助手会生成豫言源码，并检查它能否编译。':'述所欲为，助者书豫言，验其可编。','你想让程序做什么？':'欲使程序何为？','生成豫言代码':'生成豫言','仅接受豫言程序的编写与修改。需求及当前代码会发送至 DeepSeek。':'惟受豫言编修之请。所请与今稿皆传 DeepSeek。','新代码已通过编译，可应用到右侧编辑器。':'新稿已可编，可置于右。','应用代码':'用此稿','从这些开始':'可由此始','递归与阶乘 ↗':'递归阶乘 ↗','落笔成篇':'落笔成篇','示例':'示例','你好，豫言':'初识豫言','做一道算术':'试算一题','听见回响':'听其回响','待运行':'待行','程序输出':'程序所出','编译器日志':'编译之录','等待编译':'待编','显示':'展开','隐藏':'收起','运行与错误诊断':'运行与诊误','尚无诊断。':'尚无诊误。','每次运行使用独立隔离空间。暂不支持联网、交互输入与第三方包。':'每行各辟一室，今未通网、交互输入及外包。','对话与调试日志':'往来与调试之录','实时显示发送给 AI 的全部消息、AI 回复及编译与运行输出。密钥与认证标头不会显示。本页的多次请求日志会保留，刷新后清空。':'所发所答、编行之出，随至随示；不示其钥。诸次之录留于此页，刷新则去。','生成或运行后，可以在这里看到每一步。':'生成或运行后，可于此观诸步骤。','豫言 / 一种为中文而生的编程语言':'豫言 / 为中文编程而作','中文可编程，文字有回响。':'中文可编，文字可行。','仅接受本站请求':'惟受本站之请','请先写入豫言源码':'请先书豫言','编译室正忙，请稍后重试':'编译室方有事，请稍候复试','试用额度已用尽，请稍后再试':'今日之额已尽，请稍候复试','服务暂不可用，请稍后重试':'服务暂止，请稍候复试','请求格式无效':'所请格式不合','已完成':'已毕','待修正':'待改','暂不可用':'暂不可用','编译中':'编译中','运行中':'运行中','编译运行中':'正在编行','已生成通过编译的豫言程序。':'豫言新稿已成，且验其可编。','正在理解需求、生成源码并验证编译…':'正审其请，书稿而验之…','首次启动可能需要稍等。':'初启须稍候。','请阅读汉语版本。':'请阅汉语本。','暂无文言版本':'文言本尚缺','保存':'存之','复制代码':'复制此文','已复制':'已复制','复制失败，请手动选择代码。':'复制未成，请自择其文。'};
function 译(s){if(语言==='han')return s;return 词[s]||s.replace(/^编译室已就绪 · /,'编译室已备 · ').replace(/^已加载 (\d+) 个标准库模块、(\d+) 条公开签名和 (\d+) 个已验证示例$/,'已载标准库 $1 模块、$2 公开签名与 $3 已验之例').replace(/^Pro 编写与验证（第 (.*) 轮）$/,'Pro 编修与验（第 $1 轮）').replace('暂无请求 · 点击隐藏 / 显示','尚无所请 · 点击开阖').replace('未完成 · 展开查看原因','未成 · 展卷察因').replace('已完成 · 点击隐藏 / 显示','已毕 · 点击开阖').replace(/^(\d+) 字符$/,'$1 字符');}
function 存(){const 域=location.hostname==='yuyan-lang.org'||location.hostname.endsWith('.yuyan-lang.org')?'; Domain=yuyan-lang.org':'';document.cookie=`yuyan_lang=${语言}; Path=/; Max-Age=31536000; SameSite=Lax${location.protocol==='https:'?'; Secure':''}${域}`;}
const 导航=document.createElement('header');导航.className='豫导航';导航.innerHTML=`<a class="豫跳转" href="#正文">跳到正文</a><a class="豫标志" href="${主站}/" aria-label="豫言首页">豫<b>言</b></a><a class="豫站名" href="${站.dataset.home||'/'}"></a><button class="豫菜单" type="button" aria-expanded="false" aria-controls="豫导航内">菜单</button><nav class="豫导航内" id="豫导航内" aria-label="全站导航"><a href="${主站}/教程/">教程</a><a href="${主站}/文档/">文档</a><a href="${包站}">包管理</a><a href="https://github.com/yuyan-lang/yuyan">GitHub ↗</a><div class="豫语言" role="group" aria-label="界面语言"><button type="button" data-lang="han">汉语</button><button type="button" data-lang="wen">文言</button></div><a class="豫试写" href="${试写}">在线体验</a></nav>`;
document.body.prepend(导航);for(const a of 导航.querySelectorAll("nav>a")){const active=(类型==='tutorial'&&a.href===主站+'/教程/')||(类型==='docs'&&a.href===主站+'/文档/')||(类型==='packages'&&new URL(a.href).hostname===new URL(包站).hostname)||(类型==='playground'&&a.href===试写);if(active)a.setAttribute("aria-current","page");}const 正文=document.querySelector('main');if(正文&&!document.getElementById('正文'))正文.id='正文';
if(['docs','source'].includes(类型)){const 提示=document.createElement('p');提示.className='豫原文说明';提示.dataset.han='源码、类型签名和源码注释按原文显示。';提示.dataset.wen='源码、类型签名与原注皆存其本，无独立文言译本者不妄改之。';提示.textContent=提示.dataset.han;导航.after(提示);}
const 原字=new WeakMap();
function 刷(){if(!document?.body)return;document.documentElement.lang=语言==='wen'?'lzh':'zh-CN';document.documentElement.dataset.lang=语言;const 站名=(名称[类型]||名称.home)[语言==='wen'?1:0];if(导航.querySelector('.豫站名').textContent!==站名)导航.querySelector('.豫站名').textContent=站名;导航.querySelectorAll('[data-lang]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.lang===语言)));
 document.querySelectorAll('[data-han][data-wen]').forEach(e=>{const t=语言==='wen'?e.dataset.wen:e.dataset.han;if(e.textContent!==t)e.textContent=t;});
 document.querySelectorAll('[data-language-version]').forEach(e=>{e.hidden=e.dataset.languageVersion!==语言;});
 const walker=document.createTreeWalker(document.body,NodeFilter.SHOW_ELEMENT|NodeFilter.SHOW_TEXT,{acceptNode:n=>n.nodeType===1?(n.matches('script,style,code,pre,textarea,[role=log],[data-原文],[data-han],[data-language-version],.tree-name,.module-link-name,.module-title h2,.symbol-heading h3,.source-path,.breadcrumb,.symbol-description:not(.is-empty)')?NodeFilter.FILTER_REJECT:NodeFilter.FILTER_SKIP):NodeFilter.FILTER_ACCEPT});let n;while(n=walker.nextNode()){const p=n.parentElement;if(!p||p.closest('script,style,code,pre,textarea,[role=log],[data-原文],[data-han],[data-language-version],.tree-name,.module-link-name,.module-title h2,.symbol-heading h3,.source-path,.breadcrumb,.symbol-description:not(.is-empty)'))continue;const old=原字.get(n);const source=old&&n.nodeValue===old.out?old.source:n.nodeValue;const trimmed=source.trim();const out=source.replace(trimmed,译(trimmed));原字.set(n,{source,out});if(n.nodeValue!==out)n.nodeValue=out;}
 document.querySelectorAll('[data-placeholder-han]').forEach(e=>e.placeholder=语言==='wen'?e.dataset.placeholderWen:e.dataset.placeholderHan);
 document.querySelectorAll('a[data-language-peer]').forEach(a=>{a.href=语言==='wen'?a.dataset.wenHref:a.dataset.hanHref;});
}
function 设置(v){if(!['han','wen'].includes(v))return;语言=v;存();const u=new URL(location.href);u.searchParams.set('lang',v);history.replaceState(null,'',u);刷();document.dispatchEvent(new CustomEvent('豫言语言改变',{detail:v}));const peer=站.dataset[语言==='wen'?'wenPage':'hanPage'];if(peer&&new URL(peer,location.href).pathname!==location.pathname){const x=new URL(peer,location.href);x.searchParams.set('lang',v);x.hash=location.hash;location.assign(x);}}
导航.querySelectorAll('[data-lang]').forEach(b=>b.addEventListener('click',()=>设置(b.dataset.lang)));导航.querySelector('.豫菜单').addEventListener('click',e=>{const open=导航.dataset.open!=='true';导航.dataset.open=String(open);e.currentTarget.setAttribute('aria-expanded',String(open));});
window.豫言界面={译,设置语言:设置,get 语言(){return 语言}};if(参数)存();刷();let 排队=false;new MutationObserver(()=>{if(排队)return;排队=true;queueMicrotask(()=>{排队=false;刷();});}).observe(document.body,{childList:true,subtree:true,characterData:true});
if(站.dataset.hanPage||站.dataset.wenPage){const peer=站.dataset[语言==='wen'?'wenPage':'hanPage'];if(peer&&new URL(peer,location.href).pathname!==location.pathname){const u=new URL(peer,location.href);u.searchParams.set('lang',语言);u.hash=location.hash;location.replace(u);}}
})();
