# This is a basic workflow to help you get started with Actions

name: CI
env:
  YY_GC_MAX_HEAP_SIZE_MB: 400

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master , develop]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# cancel previous run on new pushes to PR
# concurrency:
#   group:  ${{ github.workflow }}-${{ github.ref }}
  # cancel-in-progress: true

jobs:
  # macos-test:
  #   runs-on: macos-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: ./.github/actions/install-mac-dependencies

  #     - name: make test
  #       run: make test

  # macos-bs-test:
  #   runs-on: macos-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: ./.github/actions/install-mac-dependencies

  #     - name: make bsrt
  #       if: '! github.event.pull_request.draft'
  #       run: make bsrt

  # macos-bs-build:
  #   runs-on: macos-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: ./.github/actions/install-mac-dependencies
  #     - name: make bsr
  #       if: '! github.event.pull_request.draft'
  #       run: make bsr

  #     - uses: actions/upload-artifact@v4
  #       with:
  #         name: macos-release-package
  #         path: |
  #           ./yy
  #           ./install.sh
  #           ./runtime/libyyrtdebug.a
  #           ./runtime/libyyrtopt.a
  #           ./yylib

  # This workflow contains a single job called "build"
  ubuntu-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/install-linux-dependencies

      - name: make test
        run: make test

  ubuntu-test-bs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/install-linux-dependencies

      - name: make test_bs
        run: make test_bs

  ubuntu-bs-test-bs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/install-linux-dependencies

      - name: make bsrt_bs
        run: make bsrt_bs

  ubuntu-bs-build-p:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/install-linux-dependencies
      - name: make bsrp
        run: make bsrp


  ubuntu-bs-build-tc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/install-linux-dependencies
      - name: make bsrtc
        run: make bsrtc

  ubuntu-bs-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/install-linux-dependencies
      - name: make yy_bs
        run: make yy_bs
      - name: make yy_bs_bs
        run: make yy_bs_bs
      - name: make yy_bs_bs_debug
        run: make yy_bs_bs_debug

      - uses: actions/upload-artifact@v4
        with:
          name: ubuntu-linux-amd64-release-package-from-yy-and-yybs
          path: |
            ./yy_bs_bs
            ./yy_bs_bs_debug
            ./.yybuild.nosync/yy_入口_豫言编译器默认执行包.opt.bc
            ./.yybuild.nosync/yy_入口_豫言编译器默认执行包.bc
            ./运行时支持库/libyyrtdebug.a
            ./运行时支持库/libyyrtdebug.so
            ./运行时支持库/libyyrtopt.a
            ./运行时支持库/libyyrtopt.so

  ubuntu-bs-build-from-bs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/install-linux-dependencies
      - name: curl yy_bs
        run: |
          curl -o yy_bs -L https://github.com/yuyan-lang/yuyan/releases/download/v0.1.0alpha4/yy_bs_bs_opt_static_2
          chmod u+x yy_bs
      - name: make yy_bs_bs
        run: ./yy_bs 豫言编译器/入口。豫  -o yy_bs_bs -c
      - name: make yy_bs_bs_debug
        run: make yy_bs_bs_debug

      - uses: actions/upload-artifact@v4
        with:
          name: ubuntu-linux-amd64-release-package
          path: |
            ./yy_bs_bs
            ./yy_bs_bs_debug
            ./.yybuild.nosync/yy_入口_豫言编译器默认执行包.opt.bc
            ./.yybuild.nosync/yy_入口_豫言编译器默认执行包.bc
            ./运行时支持库/libyyrtdebug.a
            ./运行时支持库/libyyrtdebug.so
            ./运行时支持库/libyyrtopt.a
            ./运行时支持库/libyyrtopt.so

  ubuntu-bs-bs-build-p:
    needs: ubuntu-bs-build-from-bs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/install-linux-dependencies
      - uses: actions/download-artifact@v4
        with:
          name: ubuntu-linux-amd64-release-package 
          path: .
      - name: ls -R
        run: ls -R
      - name: cp yy_bs_bs yy_bs
        run: |
          cp yy_bs_bs ./yy_bs
          chmod u+x ./yy_bs
      - name: make bsrp
        run: ./yy_bs 豫言编译器/入口。豫 --parse-only

  # ubuntu-bs-bs-build-p-debug:
  #   needs: ubuntu-bs-build-from-bs
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: ./.github/actions/install-linux-dependencies
  #     - uses: actions/download-artifact@v4
  #       with:
  #         name: ubuntu-linux-amd64-release-package 
  #         path: .
  #     - name: ls -R
  #       run: ls -R
  #     - name: cp yy_bs_bs_debug yy_bs
  #       run: |
  #         cp yy_bs_bs_debug ./yy_bs
  #         chmod u+x ./yy_bs
  #     - name: make bsrp
  #       run: ./yy_bs 豫言编译器/入口。豫 --parse-only
        

  ubuntu-bs-bs-build-tc:
    runs-on: ubuntu-latest-from-bs
    needs: ubuntu-bs-build
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/install-linux-dependencies
      - uses: actions/download-artifact@v4
        with:
          name: ubuntu-linux-amd64-release-package 
          path: .
      - name: ls -R
        run: ls -R
      - name: cp yy_bs_bs yy_bs
        run: |
          cp yy_bs_bs ./yy_bs
          chmod u+x ./yy_bs
      - name: make bsrtc
        run: ./yy_bs 豫言编译器/入口。豫 --type-check-only

  # ubuntu-bs-bs-build-tc-debug:
  #   runs-on: ubuntu-latest
  #   needs: ubuntu-bs-build-from-bs
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: ./.github/actions/install-linux-dependencies
  #     - uses: actions/download-artifact@v4
  #       with:
  #         name: ubuntu-linux-amd64-release-package 
  #         path: .
  #     - name: ls -R
  #       run: ls -R
  #     - name: cp yy_bs_bs_debug yy_bs
  #       run: |
  #         cp yy_bs_bs_debug ./yy_bs
  #         chmod u+x ./yy_bs
  #     - name: make bsrtc
  #       run: ./yy_bs 豫言编译器/入口。豫 --type-check-only

  ubuntu-bs-bs-build:
    runs-on: ubuntu-latest
    needs: ubuntu-bs-build-from-bs
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/install-linux-dependencies
      - uses: actions/download-artifact@v4
        with:
          name: ubuntu-linux-amd64-release-package 
          path: .
      - name: ls -R
        run: ls -R
      - name: mv yy_bs_bs yy_bs
        run: |
          mv yy_bs_bs ./yy_bs
          chmod u+x ./yy_bs
      - name: make yy_bs_bs
        run: make yy_bs_bs
      - name: make yy_bs_bs_debug
        run: make yy_bs_bs_debug

      - uses: actions/upload-artifact@v4
        with:
          name: ubuntu-linux-amd64-release-package-bootstrapped
          path: |
            ./yy_bs_bs
            ./yy_bs_bs_debug
            ./.yybuild.nosync/yy_入口_豫言编译器默认执行包.opt.bc
            ./.yybuild.nosync/yy_入口_豫言编译器默认执行包.bc
            ./runtime/libyyrtdebug.a
            ./runtime/libyyrtdebug.so
            ./runtime/libyyrtopt.a
            ./runtime/libyyrtopt.so